services:
  payara-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcs-ksm-hsm-payara-demo:local
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
      ENVELOPE_MODE: "local"
